import type { Metadata } from "next";
import "./globals.css";

import { Montserrat } from "next/font/google";

// Use className instead of variable
const montserrat = Montserrat({
  subsets: ["latin"],
  // This will automatically generate a class name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import RootLayoutComponent from "@/Layout/RootLayout";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <RootLayoutComponent>{children}</RootLayoutComponent>
      </body>
    </html>
  );
}
